/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Kjetil S. Matheussen.

	Well, this file could need a real clean-up, I suppose. -KSM.

 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )


extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;
extern struct GfxBase *GfxBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *Project0Wnd;
extern UWORD                 Project0Left;
extern UWORD                 Project0Top;
extern UWORD                 Project0Width;
extern UWORD                 Project0Height;
extern UBYTE                *Project0Wdt;
extern struct TextAttr       XCourier11;
extern struct IntuiText      Project0IText[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void Project0Render( void );
extern int OpenProject0Window( void );
extern void CloseProject0Window( void );
